-- Complete six-week quiz content and answer keys.
-- This migration is intentionally additive and safe to run after 0005.

alter table public.quizzes
  add column if not exists is_available boolean not null default true;

alter table public.quiz_questions
  alter column correct_option_index drop not null;

update public.courses
set passing_score = greatest(passing_score, 70);

update public.quizzes
set passing_score = greatest(passing_score, 70)
where id in ('quiz-week-1', 'quiz-week-2', 'quiz-week-3', 'quiz-week-4', 'quiz-week-5', 'quiz-week-6');

insert into public.quiz_questions (id, quiz_id, prompt, options, correct_option_index, explanation, sort_order)
values
  ('q-week-1-1', 'quiz-week-1', 'What is the main purpose of self-discovery?', '["To understand yourself more clearly", "To become exactly like successful people", "To avoid discovering your weaknesses", "To make everyone approve of you"]'::jsonb, 1, null, 1),
  ('q-week-1-2', 'quiz-week-1', 'Which question is most useful when trying to understand your personal values?', '["What principles are important to me when I make decisions?", "What is the most popular opinion around me?", "What will make me look successful?", "What do other people expect me to value?"]'::jsonb, 2, null, 2),
  ('q-week-1-3', 'quiz-week-1', 'A student enjoys solving difficult problems and feels energized when helping classmates understand mathematics. What should she investigate further during self-discovery?', '["Her friends'' career choices", "Her social media followers", "Her popularity ranking", "Her interests and strengths"]'::jsonb, 0, null, 3),
  ('q-week-1-4', 'quiz-week-1', 'Which statement best distinguishes a strength from an interest?', '["A strength and an interest always mean exactly the same thing", "A strength is something you can do well, while an interest is something you enjoy or want to explore", "A strength is always a school subject, while an interest is always a hobby", "A strength is something everyone admires, while an interest is something nobody notices"]'::jsonb, 1, null, 4),
  ('q-week-1-5', 'quiz-week-1', 'Why is identifying weaknesses important in self-discovery?', '["It gives people permission to stop trying", "It proves that a person is unsuccessful", "It allows someone to compare themselves constantly with others", "It helps a person recognize areas that may need improvement"]'::jsonb, 2, null, 5),
  ('q-week-1-6', 'quiz-week-1', 'A young person says, "I am not good at speaking in front of people yet, but I want to improve." What does this statement demonstrate?', '["Dependence on other people''s opinions", "Complete acceptance of permanent weakness", "Honest self-awareness with a growth mindset", "Lack of self-awareness"]'::jsonb, 1, null, 6),
  ('q-week-1-7', 'quiz-week-1', 'Which of the following is an example of self-awareness?', '["Ignoring feedback because it feels uncomfortable", "Assuming everyone thinks exactly as you do", "Copying a friend''s study routine without reflection", "Knowing that you become distracted when studying around your phone"]'::jsonb, 0, null, 7),
  ('q-week-1-8', 'quiz-week-1', 'Why should self-discovery not be based entirely on other people''s opinions?', '["Because successful people should never listen to anyone", "Because feedback is always harmful", "Because other people can never know anything about you", "Because your identity requires personal reflection as well as useful feedback"]'::jsonb, 2, null, 8),
  ('q-week-1-9', 'quiz-week-1', 'A participant lists activities that make her lose track of time, subjects she enjoys, and problems she likes solving. What is she primarily trying to identify?', '["Her interests", "Her financial status", "Her social reputation", "Her weaknesses only"]'::jsonb, 1, null, 9),
  ('q-week-1-10', 'quiz-week-1', 'Which approach gives the most balanced picture of your strengths and weaknesses?', '["Focus only on your weaknesses", "Use other people''s strengths as your standard", "Focus only on your strengths", "Recognize both what you do well and what you need to develop"]'::jsonb, 0, null, 10),
  ('q-week-1-11', 'quiz-week-1', 'A student is excellent at organizing group projects but assumes that because it feels easy, it is not a real strength. What should she understand?', '["Only difficult activities can be strengths", "A strength must always be recognized by everyone", "Strengths can sometimes feel natural because they are areas of capability", "Organizing is not a useful personal ability"]'::jsonb, 2, null, 11),
  ('q-week-1-12', 'quiz-week-1', 'Which activity would provide the strongest evidence when identifying a personal strength?', '["Listing only activities you wish you could do", "Choosing whatever skill is currently trending", "Selecting the skill most admired by friends", "Reviewing tasks where you consistently perform effectively"]'::jsonb, 1, null, 12),
  ('q-week-1-13', 'quiz-week-1', 'What is a healthy response after discovering a weakness?', '["Compare it with someone else''s weakness", "Decide that improvement is impossible", "Use it to identify a specific area for growth", "Hide it permanently"]'::jsonb, 0, null, 13),
  ('q-week-1-14', 'quiz-week-1', 'A young person realizes that she enjoys helping people, communicates well, and feels fulfilled when solving other people''s problems. What should she do with this discovery?', '["Use it as information when exploring future opportunities", "Assume she has only one possible career", "Ignore it because interests cannot change", "Choose the first job involving people"]'::jsonb, 2, null, 14),
  ('q-week-1-15', 'quiz-week-1', 'Why is self-discovery considered an ongoing process?', '["Because strengths and weaknesses never change", "Because nobody can ever know anything about themselves", "Because people can learn, change, and discover new aspects of themselves", "Because people should never make decisions"]'::jsonb, 1, null, 15),
  ('q-week-1-16', 'quiz-week-1', 'Which question best encourages reflection on personal strengths?', '["Who is more successful than me?", "What skill is everyone learning this year?", "What do people online say I should become?", "What do I consistently do well?"]'::jsonb, 0, null, 16),
  ('q-week-1-17', 'quiz-week-1', 'A participant discovers that impatience often causes her to interrupt others. What is the most productive use of this discovery?', '["Blame everyone who speaks slowly", "Use the awareness to practise listening and patience", "Accept it as part of her personality and never change it", "Avoid every conversation"]'::jsonb, 2, null, 17),
  ('q-week-1-18', 'quiz-week-1', 'Which statement reflects healthy self-acceptance?', '["I must be perfect before I can value myself.", "My strengths only matter when other people praise them.", "I have weaknesses, so I cannot become successful.", "I can acknowledge where I am while working to become better."]'::jsonb, 1, null, 18),
  ('q-week-1-19', 'quiz-week-1', 'What can happen when a person has a clearer understanding of their strengths, interests, and values?', '["They can make more intentional personal decisions", "They no longer need advice or learning", "They will automatically become successful", "They will never experience failure"]'::jsonb, 0, null, 19),
  ('q-week-1-20', 'quiz-week-1', 'Which statement best captures the relationship between self-discovery and personal growth?', '["Self-discovery means accepting everything about yourself without change", "Self-discovery is mainly about discovering what other people think of you", "Self-discovery provides information that can guide intentional growth", "Personal growth only begins after every weakness disappears"]'::jsonb, 2, null, 20),
  ('q-week-2-1', 'quiz-week-2', 'What is a limiting belief?', '["A useful skill that needs practice", "A goal that is difficult to achieve", "A belief that restricts what a person thinks is possible for them", "A temporary feeling of excitement"]'::jsonb, 2, null, 1),
  ('q-week-2-2', 'quiz-week-2', 'Which statement is most clearly an example of a limiting belief?', '["I need more practice before I can do this well", "I have never done this before, so I cannot learn it", "This task will require patience", "I should ask someone to teach me"]'::jsonb, 1, null, 2),
  ('q-week-2-3', 'quiz-week-2', 'A student says, "People from my background cannot become successful entrepreneurs." What should the student question first?', '["Whether entrepreneurship requires any effort", "Whether the belief is an unsupported generalization", "Whether every entrepreneur has the same personality", "Whether success should always happen quickly"]'::jsonb, 0, null, 3),
  ('q-week-2-4', 'quiz-week-2', 'What is one important effect of limiting beliefs?', '["They make every decision easier", "They automatically reveal a person''s true ability", "They guarantee that a person will fail", "They can influence people to avoid opportunities"]'::jsonb, 2, null, 4),
  ('q-week-2-5', 'quiz-week-2', 'Which response best challenges the belief, "I am not intelligent enough to succeed"?', '["My current ability does not define everything I can learn or develop", "I should stop trying difficult things", "Success is only for naturally gifted people", "Other people are simply luckier than I am"]'::jsonb, 1, null, 5),
  ('q-week-2-6', 'quiz-week-2', 'What is the first useful step when you notice a recurring thought that limits you?', '["Become aware of and identify the thought", "Blame another person for the thought", "Assume the thought must be true", "Immediately act as if the thought never existed"]'::jsonb, 0, null, 6),
  ('q-week-2-7', 'quiz-week-2', 'A young person thinks, "If I fail once, everyone will think I am a failure." Which thinking pattern should she examine?', '["Creating a daily routine", "Setting a measurable goal", "Identifying a personal strength", "Treating one event as a definition of her entire identity"]'::jsonb, 2, null, 7),
  ('q-week-2-8', 'quiz-week-2', 'What does it mean to reprogram your mind in the context of personal development?', '["Thinking positively without taking action", "Forgetting every negative experience", "Pretending that problems do not exist", "Intentionally developing healthier and more constructive thought patterns"]'::jsonb, 1, null, 8),
  ('q-week-2-9', 'quiz-week-2', 'Which statement is the strongest example of a growth-oriented thought?', '["If it is difficult, it means I am not capable", "People who succeed never struggle", "I am either talented or I am not", "I can improve this skill through learning and practice"]'::jsonb, 0, null, 9),
  ('q-week-2-10', 'quiz-week-2', 'Why is replacing an unhelpful thought with a realistic, constructive thought more useful than simply saying something you do not believe?', '["Because negative emotions should never be experienced", "Because constructive thinking should still be connected to reality", "Because problems disappear when you use positive words", "Because positive statements always guarantee success"]'::jsonb, 2, null, 10),
  ('q-week-2-11', 'quiz-week-2', 'A participant thinks, "I always procrastinate, so there is nothing I can do about it." Which response best supports mindset change?', '["Everyone procrastinates, so it does not matter", "I should avoid every responsibility", "I can identify what triggers my procrastination and practise a different response", "I will always procrastinate because it is who I am"]'::jsonb, 1, null, 11),
  ('q-week-2-12', 'quiz-week-2', 'Which question is most useful when challenging a limiting belief?', '["What evidence supports or challenges this belief?", "How can I avoid thinking about it forever?", "Who can I blame for having this thought?", "How can I make everyone agree with me?"]'::jsonb, 0, null, 12),
  ('q-week-2-13', 'quiz-week-2', 'A student receives a poor test result and thinks, "I am terrible at everything." What would be a more constructive interpretation?', '["This result shows that I need to identify what I did not understand and improve", "Everyone else is naturally better than me", "There is no point studying because I already failed", "This proves I should never attempt the subject again"]'::jsonb, 2, null, 13),
  ('q-week-2-14', 'quiz-week-2', 'How can the people around you influence your mindset?', '["They make personal responsibility unnecessary", "They determine your future automatically", "They completely control your thoughts", "Their words and expectations can influence the beliefs you develop"]'::jsonb, 1, null, 14),
  ('q-week-2-15', 'quiz-week-2', 'A young person has repeatedly heard, "You are too young to lead." Which response best demonstrates healthy mindset development?', '["I must prove everyone wrong immediately", "Leadership requires no learning", "I can develop leadership skills and demonstrate them through responsible action", "Age means I can never lead"]'::jsonb, 0, null, 15),
  ('q-week-2-16', 'quiz-week-2', 'Why should a person be careful about repeatedly saying negative things about their own ability?', '["Every negative thought immediately becomes a fact", "Repeated thoughts can influence attitudes, expectations, and behavior", "People must never acknowledge difficulties", "Negative thoughts are always completely avoidable"]'::jsonb, 2, null, 16),
  ('q-week-2-17', 'quiz-week-2', 'Which practice best supports the development of a healthier mindset?', '["Compare yourself with successful people every day", "Ignore every problem and focus only on good things", "Wait for confidence before trying anything difficult", "Notice unhelpful thoughts, question them, and choose more constructive responses"]'::jsonb, 1, null, 17),
  ('q-week-2-18', 'quiz-week-2', 'A participant changes "I am bad at speaking" to "Public speaking is a skill I can develop with practice." What has changed most directly?', '["The person has eliminated every fear", "The person has already mastered public speaking", "The person has guaranteed success", "The belief has shifted from a fixed identity statement to a development-focused view"]'::jsonb, 0, null, 18),
  ('q-week-2-19', 'quiz-week-2', 'What is the danger of accepting every thought you have as true?', '["Thoughts are never useful", "Facts should always be ignored", "People should never trust their own judgment", "Some thoughts are assumptions, interpretations, or fears rather than established facts"]'::jsonb, 2, null, 19),
  ('q-week-2-20', 'quiz-week-2', 'Which statement best summarizes the goal of a mindset reset?', '["To convince yourself that every outcome will be perfect", "To eliminate every negative emotion", "To avoid every situation that creates uncertainty", "To become aware of restrictive thinking and intentionally develop more constructive ways of thinking"]'::jsonb, 1, null, 20),
  ('q-week-3-1', 'quiz-week-3', 'What is the main purpose of creating a personal vision?', '["To copy the lifestyle of a successful person", "To avoid making decisions in the present", "To provide a clear picture of the future you want to work toward", "To guarantee that everything will happen exactly as planned"]'::jsonb, 1, null, 1),
  ('q-week-3-2', 'quiz-week-3', 'Which statement best describes the difference between a vision and a goal?', '["A vision and a goal are exactly the same thing", "A vision is always short-term, while a goal is always lifelong", "A vision requires no action, while a goal requires no planning", "A vision describes a desired future, while a goal identifies a specific result to work toward"]'::jsonb, 2, null, 2),
  ('q-week-3-3', 'quiz-week-3', 'Which question would best help a young person begin creating a personal vision?', '["What does everyone else want me to become?", "What is the easiest future I can choose?", "What kind of person and life do I want to build?", "What career is currently most popular?"]'::jsonb, 0, null, 3),
  ('q-week-3-4', 'quiz-week-3', 'Why should a personal vision be connected to personal values?', '["Values prevent goals from changing", "Values guarantee financial success", "Values make planning unnecessary", "Values help ensure the desired future reflects what is genuinely important to you"]'::jsonb, 1, null, 4),
  ('q-week-3-5', 'quiz-week-3', 'A student says, "I want to be successful." What is the biggest problem with this statement as a goal?', '["A goal should never relate to the future", "Successful people should not have goals", "It does not clearly define what success means or how it will be measured", "Success can never be achieved"]'::jsonb, 2, null, 5),
  ('q-week-3-6', 'quiz-week-3', 'In the SMART framework, what does the "S" stand for?', '["Strategic", "Simple", "Successful", "Specific"]'::jsonb, 0, null, 6),
  ('q-week-3-7', 'quiz-week-3', 'Which goal is the most specific?', '["I will improve my academic performance.", "I will study harder.", "I will become better at school.", "I will raise my mathematics test average from 60% to 75%."]'::jsonb, 1, null, 7),
  ('q-week-3-8', 'quiz-week-3', 'Which feature makes a goal measurable?', '["It is written in one sentence", "It sounds inspiring", "It is difficult to achieve", "It includes a way to track progress or determine the result"]'::jsonb, 2, null, 8),
  ('q-week-3-9', 'quiz-week-3', 'A student sets the goal, "I will read 12 books by December 31." Which SMART element is most clearly demonstrated by "by December 31"?', '["Achievable", "Specific", "Relevant", "Time-bound"]'::jsonb, 0, null, 9),
  ('q-week-3-10', 'quiz-week-3', 'Why is the "Achievable" part of a SMART goal important?', '["It means the goal should never require learning anything new", "It ensures the goal is realistically possible within the circumstances and resources available", "It guarantees the goal will succeed", "It means the goal must be extremely easy"]'::jsonb, 1, null, 10),
  ('q-week-3-11', 'quiz-week-3', 'What does "Relevant" mean in a SMART goal?', '["The goal must be completed immediately", "The goal must be the most difficult option available", "The goal connects to something meaningful and important to the person''s broader direction", "The goal must be popular with everyone"]'::jsonb, 2, null, 11),
  ('q-week-3-12', 'quiz-week-3', 'Which of the following is the strongest SMART goal?', '["I will exercise more.", "I will become healthier someday.", "I will walk for 30 minutes four days a week for the next six weeks.", "I will try to exercise whenever possible."]'::jsonb, 0, null, 12),
  ('q-week-3-13', 'quiz-week-3', 'A young person has a vision of becoming a respected community leader. Which goal best supports that vision?', '["I will improve my leadership skills by completing one leadership course within three months.", "People will respect me someday.", "I will become famous this year.", "I will wait until someone gives me a leadership position."]'::jsonb, 1, null, 13),
  ('q-week-3-14', 'quiz-week-3', 'Why is it useful to break a large vision into smaller goals?', '["It guarantees that there will be no obstacles", "It means long-term thinking is unnecessary", "It makes the vision less important", "It turns a broad desired future into manageable results and actions"]'::jsonb, 2, null, 14),
  ('q-week-3-15', 'quiz-week-3', 'A student wants to save NGN 60,000 in six months. Which part of the goal makes progress easiest to measure?', '["The student''s hope to succeed", "The fact that saving is important", "The student''s desire to save", "The target amount of NGN 60,000"]'::jsonb, 0, null, 15),
  ('q-week-3-16', 'quiz-week-3', 'Which statement about goals is most accurate?', '["Changing a goal always means a person has failed", "Goals should only be changed when someone else tells you to", "Goals can be adjusted when circumstances change while still keeping the broader direction in mind", "A goal must never change under any circumstance"]'::jsonb, 1, null, 16),
  ('q-week-3-17', 'quiz-week-3', 'A student''s vision is to become financially independent. Which goal is most directly connected to that vision?', '["I hope people think I am wealthy.", "I will wait for a wealthy person to help me.", "I will buy expensive clothes this year.", "I will learn one income-generating skill and practise it for five hours each week for three months."]'::jsonb, 2, null, 17),
  ('q-week-3-18', 'quiz-week-3', 'What is the main problem with setting too many major goals at the same time?', '["Having more than one goal is always wrong", "Goals only work when they are secret", "Attention and resources can become divided across too many priorities", "One goal automatically prevents success in another"]'::jsonb, 0, null, 18),
  ('q-week-3-19', 'quiz-week-3', 'Which action best connects a vision to daily life?', '["Thinking about the vision only once a year", "Waiting for motivation before doing anything", "Choosing daily actions that contribute toward meaningful goals linked to the vision", "Changing the vision whenever an activity becomes difficult"]'::jsonb, 1, null, 19),
  ('q-week-3-20', 'quiz-week-3', 'Which sequence best turns a desired future into practical action?', '["Vision -> waiting -> success -> goals", "Goals -> confusion -> vision -> action", "Vision -> goals -> specific actions -> progress tracking", "Action -> vision -> avoidance -> goals"]'::jsonb, 2, null, 20),
  ('q-week-4-1', 'quiz-week-4', 'What is the best description of discipline?', '["Doing something only when you feel motivated", "The ability to consistently do what needs to be done, even when you don''t feel like it", "Avoiding everything that is difficult and looking for easier ways to achieve big tasks", "Working continuously without resting ensuring you have your mind on the end result"]'::jsonb, 1, 'Discipline means following through on what matters even when motivation is low.', 1),
  ('q-week-4-2', 'quiz-week-4', 'David says, "I will study when I feel motivated." What is the biggest problem with this approach?', '["Studying requires too much energy", "Motivation is not always available when action is required", "Studying should be timed and acted upon immediately", "He needs to surround himself with more books"]'::jsonb, 1, 'Motivation can help you start, but discipline helps you continue when motivation disappears.', 2),
  ('q-week-4-3', 'quiz-week-4', 'Which of the following is most likely to weaken a person''s discipline?', '["Having clear priorities against all odds", "Creating a realistic schedule", "Constantly giving in to distractions", "Tracking progress and defending it"]'::jsonb, 2, 'Repeatedly allowing distractions to control your attention makes it harder to stay committed to important tasks.', 3),
  ('q-week-4-4', 'quiz-week-4', 'Sarah has three important assignments but spends two hours scrolling through social media before starting. What should she address first?', '["Her handwriting", "Her environment and distractions", "The colour of her books", "Her assignments"]'::jsonb, 1, 'Discipline is easier when you reduce the distractions competing for your attention.', 4),
  ('q-week-4-5', 'quiz-week-4', 'Which statement about procrastination is most accurate?', '["Procrastination means being lazy all the time", "Procrastination is delaying an important task even though you know it needs to be done", "Procrastination is taking a short break", "Procrastination means changing your goals"]'::jsonb, 1, 'The issue is unnecessary delay-not taking appropriate rest.', 5),
  ('q-week-4-6', 'quiz-week-4', 'James creates a plan to study for six hours every day, but he usually becomes exhausted after two days. What is the better approach?', '["Quit studying completely", "Create a smaller, realistic routine he can maintain consistently", "Study only when exams are near", "Blame himself for lacking discipline"]'::jsonb, 1, 'A sustainable routine is more useful than an unrealistic plan that quickly collapses.', 6),
  ('q-week-4-7', 'quiz-week-4', 'Which of the following shows discipline?', '["Completing your work only when someone threatens you", "Waiting until the deadline before starting", "Following your planned routine even when you would rather do something else", "Changing your goals whenever they become difficult"]'::jsonb, 2, 'Discipline involves choosing actions that support your goals instead of always choosing what feels easiest.', 7),
  ('q-week-4-8', 'quiz-week-4', 'A student wants to improve academically. Which action would BEST support discipline?', '["Waiting until examination week", "Creating specific study times and protecting them", "Studying whenever friends are studying", "Reading only subjects the student enjoys"]'::jsonb, 1, 'Planned and protected study periods make it easier to turn intention into consistent action.', 8),
  ('q-week-4-9', 'quiz-week-4', 'What is one major difference between motivation and discipline?', '["Motivation is always stronger than discipline", "Discipline does not require any goals", "Motivation can change with feelings, while discipline helps you act despite changing feelings", "They mean exactly the same thing"]'::jsonb, 2, 'Motivation fluctuates. Discipline helps you remain committed even when your feelings change.', 9),
  ('q-week-4-10', 'quiz-week-4', 'Which question would be most useful when trying to improve your discipline?', '["\"What excuse can I use today?\"", "\"How can I avoid difficult tasks?\"", "\"Who is responsible for my failure?\"", "\"What is one action I need to consistently take?\""]'::jsonb, 3, 'Discipline grows when you identify the specific behaviour that needs to become consistent.', 10),
  ('q-week-4-11', 'quiz-week-4', 'What is a habit?', '["Something you do once", "A behaviour that becomes increasingly automatic through repetition and consistent cues", "A goal you have written down", "Something you do only when you are rewarded"]'::jsonb, 1, 'Repeated behaviour in a consistent context can become easier and more automatic over time.', 11),
  ('q-week-4-12', 'quiz-week-4', 'Michael wants to develop a reading habit. Which plan is BEST?', '["\"I will read 10 pages after dinner every evening.\"", "\"I will read more someday\"", "\"I will read whenever I have nothing else to do.\"", "\"I will finish 10 books tomorrow.\""]'::jsonb, 0, 'The plan is specific, realistic and connected to a consistent time or routine.', 12),
  ('q-week-4-13', 'quiz-week-4', 'Why is starting small often helpful when building a new habit?', '["Small actions do not matter", "Small actions are easier to repeat consistently", "Small actions guarantee immediate success", "Small actions require no discipline"]'::jsonb, 1, 'A behaviour that is manageable enough to repeat gives you more opportunities to build consistency.', 13),
  ('q-week-4-14', 'quiz-week-4', 'Chika wants to develop a habit of exercising every morning. Which strategy could help?', '["Keep her exercise clothes hidden in a cupboard", "Prepare her exercise clothes the night before", "Decide every morning whether she feels motivated", "Exercise only when friends invite her"]'::jsonb, 1, 'Preparing the environment in advance reduces friction and makes the desired action easier to begin.', 14),
  ('q-week-4-15', 'quiz-week-4', 'Which is the BEST example of linking a new habit to an existing routine?', '["\"I will exercise sometime this year.\"", "\"After brushing my teeth in the morning, I will do five minutes of stretching.\"", "\"I will exercise when I remember.\"", "\"I will exercise for five hours every weekend.\""]'::jsonb, 1, 'Connecting a new behaviour to an existing routine provides a reliable cue.', 15),
  ('q-week-4-16', 'quiz-week-4', 'A student wants to stop checking social media every few minutes while studying. What would be the BEST environmental change?', '["Keep the phone beside the textbook", "Put the phone away or switch off distracting notifications", "Turn off the phone volume", "Check social media before every question"]'::jsonb, 1, 'Changing the environment can remove cues and reduce easy access to distractions.', 16),
  ('q-week-4-17', 'quiz-week-4', 'David misses his new habit for one day. What should he do?', '["Return to the habit as soon as possible", "Wait until the next month to restart", "Give up as it will take him a lot to start all over again", "Double the habit for the next seven days"]'::jsonb, 0, 'Missing one day does not have to become abandoning the habit. The important thing is returning to the routine.', 17),
  ('q-week-4-18', 'quiz-week-4', 'Which of these is the strongest example of an if-then plan?', '["\"I want to become disciplined.\"", "\"I hope I can study more.\"", "\"If I finish dinner at 7 p.m., then I will study for 30 minutes.\"", "\"I will probably study tonight.\""]'::jsonb, 2, 'An if-then plan connects a specific situation or cue to a planned action and can help translate intentions into behaviour.', 18),
  ('q-week-4-19', 'quiz-week-4', 'Which approach is MOST likely to help a young person build a lasting daily habit?', '["Changing the routine every day", "Depending completely on motivation", "Choosing a clear behaviour and repeating it consistently in a stable context", "Setting the biggest possible target immediately"]'::jsonb, 2, 'Consistency and repetition in a stable context help strengthen the connection between a cue and a behaviour.', 19),
  ('q-week-4-20', 'quiz-week-4', 'Tunde wants to become more disciplined, improve his grades and develop a reading habit. Which plan demonstrates the BEST understanding of this week''s lesson?', '["Set ten major goals and try to change everything immediately", "Wait until he feels motivated before beginning", "Choose a few specific actions, schedule them, reduce distractions and repeat them consistently", "Focus only on his final results without changing his daily behaviour"]'::jsonb, 2, 'Lasting improvement comes from turning goals into specific behaviours and making those behaviours easier to repeat consistently.', 20),
  ('q-week-5-1', 'quiz-week-5', 'What is confidence?', '["Believing in yourself so much that you will never make mistakes", "Trusting your ability to learn, respond and handle challenges", "Ensuring you keep being better than everyone else", "Never feeling afraid"]'::jsonb, 1, 'Confidence does not mean you will never fail or feel afraid. It means you trust yourself enough to try, learn and keep growing.', 1),
  ('q-week-5-2', 'quiz-week-5', 'Which statement about fear is most accurate?', '["Fear always means you should stop", "Fear means you are weak", "Fear can be present even when taking the right action", "Confident people never experience fear"]'::jsonb, 2, 'Fear is a normal human response. Courage often means taking meaningful action despite fear.', 2),
  ('q-week-5-3', 'quiz-week-5', 'David wants to speak during a school presentation but is afraid people will laugh at him. What would be the most productive response?', '["Avoid all future presentations", "Tell himself that everyone must like him", "Prepare, practise and gradually face the situation", "Pretend that he is not nervous"]'::jsonb, 2, 'Preparation and gradual action can help you face situations that make you uncomfortable.', 3),
  ('q-week-5-4', 'quiz-week-5', 'Which thought is most likely to increase fear?', '["\"I can prepare and improve like my life depends on it\"", "\"I may make mistakes, but hopefully I can learn.\"", "\"If I fail once, my life is over.\"", "\"I can ask for help if I need it.\""]'::jsonb, 2, 'Catastrophic thinking makes a challenge appear much bigger than it really is.', 4),
  ('q-week-5-5', 'quiz-week-5', 'A student says, "I am not confident enough to apply for this opportunity." What would be the best response?', '["\"Then don''t apply.\"", "\"Wait until you become completely confident.\"", "\"Prepare yourself and apply even if you feel nervous.\"", "\"Someone else is probably better than you so it is normal.\""]'::jsonb, 2, 'Confidence often grows through experience. Waiting to feel completely confident can keep you stuck.', 5),
  ('q-week-5-6', 'quiz-week-5', 'Which action is most likely to build confidence over time?', '["Taking small challenges and learning from the results", "Comparing yourself constantly with others", "Taking calculated risks", "Pretending you know everything"]'::jsonb, 0, 'Successfully handling challenges-and learning from setbacks-can strengthen your belief in your ability to act.', 6),
  ('q-week-5-7', 'quiz-week-5', 'Chisom fails her first attempt at a business idea. Which response demonstrates a healthy mindset?', '["\"I have failed, so I am a failure.\"", "\"I will examine what went wrong and try again differently.\"", "\"I should never try anything again.\"", "\"Successful people never fail.\""]'::jsonb, 1, 'A setback can provide information that helps you improve your next attempt.', 7),
  ('q-week-5-8', 'quiz-week-5', 'Which of the following is an example of fear of failure?', '["Practising before an examination", "Asking someone for feedback", "Refusing to try because you might not succeed", "Learning from a mistake"]'::jsonb, 2, 'Fear of failure becomes limiting when it prevents you from taking reasonable opportunities.', 8),
  ('q-week-5-9', 'quiz-week-5', 'What is the difference between confidence and arrogance?', '["Confidence means believing you can grow; arrogance assumes you are superior to others", "Confidence means never listening to others", "Arrogance means being shy", "There is no difference"]'::jsonb, 0, 'Confidence can coexist with humility, learning and respect for others.', 9),
  ('q-week-5-10', 'quiz-week-5', 'Which statement demonstrates self-confidence?', '["\"I must be perfect before I start.\"", "\"Everyone must approve of me.\"", "\"I may not know everything yet, but I can learn.\"", "\"I am better than everyone here.\""]'::jsonb, 2, 'Healthy confidence recognizes your capacity to learn and improve.', 10),
  ('q-week-5-11', 'quiz-week-5', 'Why is taking action important?', '["Ideas automatically become results", "Action turns intentions and plans into real progress", "Action guarantees success", "Planning is unnecessary"]'::jsonb, 1, 'A goal remains an intention until you begin doing something that moves you toward it.', 11),
  ('q-week-5-12', 'quiz-week-5', 'Which person is most likely to make progress?', '["Someone who constantly plans but never starts", "Someone who waits for the perfect opportunity", "Someone who starts with a realistic first step", "Someone who changes goals every week"]'::jsonb, 2, 'Progress begins when planning is converted into action.', 12),
  ('q-week-5-13', 'quiz-week-5', 'Tolu wants to start a small fashion business but feels overwhelmed. What should she do first?', '["Build a huge company immediately", "Give up until she has everything figured out", "Identify one small action she can take this week", "Wait until someone gives her permission"]'::jsonb, 2, 'Breaking a big goal into a manageable first step makes action easier.', 13),
  ('q-week-5-14', 'quiz-week-5', 'Which is an example of procrastination?', '["Researching before making a decision", "Taking a necessary break", "Repeatedly postponing an important task without a good reason", "Adjusting a plan after receiving new information"]'::jsonb, 2, 'Procrastination is unnecessary delay, especially when you know the task is important.', 14),
  ('q-week-5-15', 'quiz-week-5', 'What should you do when you don''t know exactly how to accomplish a goal?', '["Never begin", "Start learning and take the first reasonable step", "Wait until you know everything", "Abandon the goal"]'::jsonb, 1, 'You don''t need to know every step before taking the first one.', 15),
  ('q-week-5-16', 'quiz-week-5', 'Which behaviour shows initiative?', '["Waiting for someone to tell you what to do", "Complaining about a problem without offering a solution", "Identifying something that needs to be done and taking responsible action", "Avoiding responsibility"]'::jsonb, 2, 'Initiative means taking responsible action rather than always waiting for someone else.', 16),
  ('q-week-5-17', 'quiz-week-5', 'Amaka wants to improve her public speaking. Which is the BEST first action?', '["Decide she is naturally bad at speaking", "Practise speaking in front of a mirror or trusted person", "Wait until she is invited to speak publicly", "Avoid speaking completely"]'::jsonb, 1, 'Small, deliberate practice creates experience and can gradually build confidence.', 17),
  ('q-week-5-18', 'quiz-week-5', 'What should you do when an action you take does not produce the expected result?', '["Immediately conclude that you cannot succeed", "Blame everyone else", "Evaluate what happened, learn from it and adjust your approach", "Stop pursuing every goal"]'::jsonb, 2, 'Taking action does not mean getting everything right the first time. Learning and adjusting are part of progress.', 18),
  ('q-week-5-19', 'quiz-week-5', 'Which statement best connects confidence and action?', '["You must have complete confidence before taking action", "Taking meaningful action can help develop confidence through experience", "Confidence makes action unnecessary", "Fear and action cannot exist together"]'::jsonb, 1, 'Confidence and action can reinforce each other. Taking appropriate challenges and learning from them can strengthen your belief in your abilities.', 19),
  ('q-week-5-20', 'quiz-week-5', 'Which approach BEST represents the lesson of Week 5?', '["Wait until fear disappears before pursuing your goals", "Think positively but avoid difficult situations", "Recognize fear, prepare yourself, take action, learn and keep moving", "Avoid failure at all costs"]'::jsonb, 2, 'Confidence is not the absence of fear. It is the willingness to move forward, learn and grow.', 20),
  ('q-week-6-1', 'quiz-week-6', 'What is a personal brand?', '["A logo designed for yourself", "The reputation and identity you intentionally build around who you are, what you value and what you can offer", "The number of followers you have", "The clothes you wear"]'::jsonb, 1, 'Your personal brand is about the identity, values, strengths and reputation associated with you.', 1),
  ('q-week-6-2', 'quiz-week-6', 'Which of the following is NOT enough to build a strong personal brand?', '["Knowing your strengths", "Demonstrating your values", "Consistently developing useful skills", "Having many social-media followers"]'::jsonb, 3, 'Followers alone do not define your personal brand. Your character, skills, values and reputation matter.', 2),
  ('q-week-6-3', 'quiz-week-6', 'Why is self-awareness important when building a personal brand?', '["It helps you copy successful people", "It helps you understand your strengths, values and what makes you unique", "It guarantees popularity", "It eliminates the need to develop skills"]'::jsonb, 1, 'You cannot intentionally build your brand if you do not understand what you stand for.', 3),
  ('q-week-6-4', 'quiz-week-6', 'Which statement BEST describes a strong personal brand?', '["\"I want everyone to like me.\"", "\"I am trying to look successful.\"", "\"I am known for reliability, creativity and using my skills to solve problems.\"", "\"I have the most followers.\""]'::jsonb, 2, 'A strong brand communicates clear qualities and values that are demonstrated consistently.', 4),
  ('q-week-6-5', 'quiz-week-6', 'David says he is hardworking, but he regularly misses deadlines. What is the problem?', '["His brand is being communicated inconsistently", "He needs more followers", "His clothes are inappropriate", "He needs a new social-media account"]'::jsonb, 0, 'Your actions should support the reputation you claim to have.', 5),
  ('q-week-6-6', 'quiz-week-6', 'Which factor should influence the personal brand you build?', '["Your values, strengths, skills and goals", "Whatever is trending online", "What everyone else is doing", "The desire to impress people"]'::jsonb, 0, 'Your personal brand should be rooted in who you are and where you are intentionally going.', 6),
  ('q-week-6-7', 'quiz-week-6', 'A student wants to become known as a reliable leader. Which behaviour would BEST support that brand?', '["Making promises and forgetting them", "Taking responsibility and following through on commitments", "Talking about leadership constantly", "Trying to control everyone"]'::jsonb, 1, 'Your reputation is strengthened when your behaviour consistently supports the qualities you want to be known for.', 7),
  ('q-week-6-8', 'quiz-week-6', 'What is the best way to build credibility?', '["Make big claims about yourself", "Consistently demonstrate your skills and character", "Pretend to have experience you don''t have", "Copy someone else''s achievements"]'::jsonb, 1, 'Credibility grows when people can see evidence of your skills, reliability and character.', 8),
  ('q-week-6-9', 'quiz-week-6', 'Which online behaviour can damage a person''s personal brand?', '["Sharing useful knowledge", "Communicating respectfully", "Posting content that consistently contradicts the values they claim to represent", "Learning new skills"]'::jsonb, 2, 'Your online presence contributes to how people perceive you. Your digital behaviour should align with the reputation you want to build.', 9),
  ('q-week-6-10', 'quiz-week-6', 'What is a personal brand statement primarily designed to communicate?', '["Your entire life story", "Who you are, what you offer and what differentiates you", "Your favourite hobbies only", "Your social-media password"]'::jsonb, 1, 'A good brand statement communicates your value and helps others quickly understand what you represent.', 10),
  ('q-week-6-11', 'quiz-week-6', 'What is a life system?', '["A complicated list of everything you want to do", "A practical structure that helps you organize your goals, habits, priorities and responsibilities", "A timetable that never changes", "A list of your achievements"]'::jsonb, 1, 'A life system helps turn your intentions into repeatable routines and actions.', 11),
  ('q-week-6-12', 'quiz-week-6', 'Why is having a life system useful?', '["It removes every problem from your life", "It helps you manage your priorities and make consistent progress", "It guarantees success", "It means you never need to change your plans"]'::jsonb, 1, 'A good system creates structure while still allowing you to adapt when circumstances change.', 12),
  ('q-week-6-13', 'quiz-week-6', 'Which combination BEST represents a personal life system?', '["Goals + priorities + routines + habits + review", "Dreams + excuses + distractions", "Social media + entertainment + sleep", "Motivation + luck + popularity"]'::jsonb, 0, 'Your goals tell you where you want to go; your routines and habits help you move there.', 13),
  ('q-week-6-14', 'quiz-week-6', 'Ada has many goals but rarely completes them. What would help her most?', '["Add even more goals", "Identify priorities and connect them to specific daily or weekly actions", "Wait for motivation", "Stop setting goals"]'::jsonb, 1, 'A life system converts broad goals into manageable actions and priorities.', 14),
  ('q-week-6-15', 'quiz-week-6', 'Which is an example of a daily system?', '["\"I want to be successful.\"", "\"Every evening, I review tomorrow''s priorities and prepare what I need.\"", "\"I hope my future is better.\"", "\"I will become successful someday.\""]'::jsonb, 1, 'A system is something you repeatedly do to support your larger goals.', 15),
  ('q-week-6-16', 'quiz-week-6', 'Why should your life system be reviewed regularly?', '["Because every plan must remain exactly the same", "To identify what is working, what is not working and what needs adjustment", "To create more work", "To compare yourself with others"]'::jsonb, 1, 'Your life changes. A useful system should be reviewed and adjusted as your goals, responsibilities and circumstances change.', 16),
  ('q-week-6-17', 'quiz-week-6', 'Tunde''s goal is to improve academically. Which system is most useful?', '["Study only when examinations are close", "Set study periods, track assignments, review progress weekly and adjust when necessary", "Buy more textbooks without studying", "Depend entirely on classmates"]'::jsonb, 1, 'The system connects the goal to regular behaviours and progress checks.', 17),
  ('q-week-6-18', 'quiz-week-6', 'How should your personal brand connect with your life system?', '["Your brand should be completely separate from your daily behaviour", "Your daily habits and decisions should reinforce the person you want to become", "Your brand should only exist online", "Your life system should focus only on appearance"]'::jsonb, 1, 'If you want to be known as disciplined, reliable and excellent, your daily systems should help you consistently demonstrate those qualities.', 18),
  ('q-week-6-19', 'quiz-week-6', 'Which person has the strongest life system?', '["Someone who has many goals but no routines", "Someone who relies entirely on motivation", "Someone who knows their priorities, schedules important actions, develops supporting habits and reviews progress", "Someone who changes direction every time things become difficult"]'::jsonb, 2, 'A strong life system connects direction with consistent action and regular review.', 19),
  ('q-week-6-20', 'quiz-week-6', 'Which statement BEST summarizes Week 6?', '["Your personal brand is what you post online and whom people believe you to be", "Success depends only on having ambitious goals and working hard daily to achieve it", "Build a clear identity, align your behaviour with it, create systems that support your priorities and consistently review your progress.", "Once you create a plan, you never need to change it."]'::jsonb, 2, 'Your brand is built through what you consistently demonstrate, while your life system helps you turn your intentions into daily action.', 20)
on conflict (id) do update set
  quiz_id = excluded.quiz_id,
  prompt = excluded.prompt,
  options = excluded.options,
  correct_option_index = excluded.correct_option_index,
  explanation = excluded.explanation,
  sort_order = excluded.sort_order;

update public.quizzes as quiz
set is_available = exists (
  select 1 from public.quiz_questions question where question.quiz_id = quiz.id
)
and not exists (
  select 1 from public.quiz_questions question
  where question.quiz_id = quiz.id and question.correct_option_index is null
)
where quiz.id in ('quiz-week-1', 'quiz-week-2', 'quiz-week-3', 'quiz-week-4', 'quiz-week-5', 'quiz-week-6');
